# LINEAR SEARCH / BRUTE SEARCH




                                                                            # PROBLEM 1

# 'ALICE HAS SOME CARDS WITH NUMBERS WRITTEN ON THEM. SHE ARRANGES THE CARD IN DECREASING ORDER, AND LAYS THEM OUT FACE DOWN IN A SEQUENCE ON A TABLE. SHE CHALLENGES BOB TO PICK OUT THE CARD CONTAINING A GIVEN NUMBER BY TURNING OVER AS FEW CARDS AS POSSIBLE. WRITE A FUNCTION TO HELP BOB LOCATE THE CARD.'



